spring:
  datasource:
    # url: "jdbc:mysql://localhost:3306/servicedb"
    url: "jdbc:mysql://mysql-service:3306/servicedb"
    username: "myuser"
    password: "mypassword"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    data: import.sql
  jpa:
    hibernate:
      ddl-auto: "create"
    show-sql: false

conversion:
  api: http://convrt:8069/convert
